  # frontend:
  #   build: 
  #     context: ./FE_dashboard
  #     dockerfile: Dockerfile
  #   container_name: FE_dashboard
  #   ports:
  #     - "3000:80"
  #   depends_on:
  #     - db
  #     - simulator
  #   restart: unless-stopped

services:
  simulator:
    image: mars-iot-simulator:multiarch_v1
    container_name: mars_simulator
    ports:
      - "8080:8080"
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: DB_history
    environment:
      POSTGRES_USER: mars_user
      POSTGRES_PASSWORD: mars_password
      POSTGRES_DB: mars_iot_db
    ports:
      - "5432:5432"
    volumes:
      - ./DB_history/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: mars_broker
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5672:5672"   # Porta di comunicazione per i microservizi
      - "15672:15672" # Porta per la dashboard visiva di RabbitMQ (Aprila nel browser!)
    restart: unless-stopped

  be_ingestion:
    build: 
      context: ./BE_data-ingestion
      dockerfile: Dockerfile
    container_name: BE_data-ingestion
    environment:
      - RABBITMQ_HOST=rabbitmq
      - SIMULATOR_URL=http://simulator:8080                 
      - SIMULATOR_WS_URL=ws://simulator:8080/api/telemetry/ws
    depends_on:
      - simulator
      - rabbitmq
    restart: unless-stopped

  be_processing:
    build:
      context: ./BE_processing
      dockerfile: Dockerfile
    container_name: BE_processing
    environment:
      - RABBITMQ_HOST=rabbitmq
      - SIMULATOR_URL=http://simulator:8080
      - PYTHONUNBUFFERED=1
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_started
    restart: unless-stopped

  be_presentation:
    build: 
      context: ./BE_presentation
      dockerfile: Dockerfile
    container_name: BE_presentation
    environment:
      - RABBITMQ_HOST=rabbitmq
    stdin_open: true # <--- Aggiungi queste due righe per evitare
    tty: true
    ports:
      - "8000:8000" # Porta esposta per far collegare il frontend
    depends_on:
      - rabbitmq
      - db
    restart: unless-stopped

  frontend:
    build: 
      context: ./FE_dashboard
      dockerfile: Dockerfile.dev 
    container_name: FE_dashboard
    ports:
      - "5173:5173" 
    volumes:
      - ./FE_dashboard:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true 
    depends_on:
      - simulator
      - be_presentation
    restart: unless-stopped